### ISSUE TITLE
Fix /dotablog text preview

### ISSUE THREAD

**Issue by TimJentzsch** [zachkont/dotaUpdatesBot#19]
###  The preview text of the /dotablog command doesn't display properly.
-------
- Special characters are displayed as their Unicode code,
- Links are displayed as their HTML tag.
 
The entire preview text is surrounded by

```
[u' _TEXT_  ' , u'; <_HTML_LINK_ >']...
```
so probably a text to Unicode parsing error in python?

**Comment by zachkont** [comment]
Good catch! Sounds like there's an encode() missing

**Comment by TimJentzsch** [comment]
@zachkont looks like @MurphyMark already fixed it in #22

**Comment by Pr00bit** [comment]
hi there, I am new to open contribution, can I help with the issue?
