### ISSUE TITLE
Add /help

### ISSUE THREAD

**Issue by TimJentzsch** [zachkont/dotaUpdatesBot#26]
The README.md suggests that there is a `/help` command, but it doesn't get suggested when typing `/` and when writing `/help` it only displays the welcoming message.

**Comment by zachkont** [comment]
Can you suggest an outline of what the help command should do?

**Comment by TimJentzsch** [comment]
Since it is listed in the [README.md](README.md) I thought you already had something in mind.
So I guess either removing it from that list and have it do nothing, or having it give an overview on how to use the bot, what the commands do, etc.
Not sure how useful that is though, considering that the command suggestions already provide that information.

Do you have any other ideas?

**Comment by TimJentzsch** [comment]
Closed via c070edec6e85501ff3751685e4847c7d2f08573a.
