### ISSUE TITLE
Improve /dotanews display

### ISSUE THREAD

**Issue by TimJentzsch** [zachkont/dotaUpdatesBot#28]
As of now, the text is formatted as code. Probably a normal text formatting would be better suited for the news. 

Either way, these things should get fixed:
1. Add proper word wrapping. 
Currently, the sentences are just cut off mid-word.
2. Remove empty space. 
Currently, the parsing leaves a lot of empty space at the beginning of the news.

Link to the current [Steam News](http://store.steampowered.com/news/34534/)
Screenshot of the current output:

![Current Output](https://user-images.githubusercontent.com/13908946/32700009-fe77e2d2-c7be-11e7-9db2-1e327e7653c4.PNG)

**Comment by zachkont** [comment]
The text format is just to differentiate from normal messaging. I kinda prefer it that way

The wrapping is the regular message wrap that depends on your screen width/device. That is handled by the telegram client, not much to be done

The empty space will be fixed asap

**Comment by TimJentzsch** [comment]
Ah, ok, I thought a change to normal formatting would fix the wrap issue, but apparently it is only like this on the Web version of Telegram.
Most users probably use the mobile version anyway, so it won't matter that much. 
I will have to wait for a new steam update to confirm this behaviour.

**Comment by TimJentzsch** [comment]
Closed via b9e6196.
