### ISSUE TITLE
Improve /dotanews display

### ISSUE THREAD

**Issue by TimJentzsch** [zachkont/dotaUpdatesBot#32]
Just a small QoL improvement:
Only display `[...]` when the text preview actually can't display all changes.

[Steam News](http://store.steampowered.com/news/34534/)
Screenshot:

![Current Output](https://user-images.githubusercontent.com/13908946/32703763-dba61d82-c7fa-11e7-9f92-3c7b20f6e1f7.PNG)

**Comment by zachkont** [comment]
Sounds nice but it's not that simple because the feed only contains the text that is printed. Which means you would have to follow the actual link and diff against that. Will leave open in case someone else wants to do it

**Comment by TimJentzsch** [comment]
Turns out that the `[...]` can be removed entirely, as Telegram / the parser adds `...` automatically when the content surpasses the max character limit.

[Steam News](http://store.steampowered.com/news/34739/)
Preview:
![Preview](https://user-images.githubusercontent.com/13908946/33117227-eca8a34c-cf67-11e7-901c-4bd0bc48349e.png)

**Comment by zachkont** [comment]
Good point
