### ISSUE TITLE
Improve reddit post display

### ISSUE THREAD

**Issue by TimJentzsch** [zachkont/dotaUpdatesBot#37]
Currently, everything gets previewed twice, first as code text preview and then as link preview.
The link one looks a bit better in my opinion, but doesn't remove the formatting strings, the code text preview contains unimportant information from reddit, such as 
` submitted by    /u/SirBelvedere    to    r/DotA2   [link] [comments]`.

So one of them should be removed and improved accordingly.

Screenshots: 
![Sir Belvedere](https://user-images.githubusercontent.com/13908946/32937785-214fdea4-cb7a-11e7-905e-1d1a4c9f1864.png)

![wykrhm](https://user-images.githubusercontent.com/13908946/32937763-0c13675e-cb7a-11e7-95a7-4428308abac0.png)

**Comment by zachkont** [comment]
True

**Comment by BenHargreaves** [comment]
Taking a look at this now and it seems to be a pretty quick fix.

The 'Link' preview is generated by the Telegram itself I believe so not much we can do there, but the 'Code' message can be stripped of the 'Submitted by ....' fairly easily. I can have a PR up for review after work today :)

**Comment by BenHargreaves** [comment]
Created PR #57 to address this.  Let me know if I need to change anything

**Comment by zachkont** [comment]
Looks good, merged
