### ISSUE TITLE
Replace try-except with proper checks

### ISSUE THREAD

**Issue by zachkont** [zachkont/dotaUpdatesBot#4]
Right now every call to the telegram API is within try-except blocks that just catch everything. Further investigation is required to either remove or refine those checks

**Comment by matheuscr30** [comment]
Can I do This?

**Comment by evan-schiewe** [comment]
The pyTelegramBotAPI currently raises an APIExceptions for errors, documented in the _check_result method in apihelper.py.  These are the causes:

```
A result is considered invalid if:
        - The server returned an HTTP response code other than 200
        - The content of the result is invalid JSON.
        - The method call was unsuccessful (The JSON 'ok' field equals False)

```

Do you want more specific logging / error messages in these cases?  I don't think any of the try blocks should be entirely removed because the bot api can always throw exceptions related to connectivity.

**Comment by zachkont** [comment]
More specific logging is preferred and I agree with keeping the try blocks. The main idea is to change from generic error catching to a more refined one.

**Comment by Double-A-92** [comment]
I'm trying to do a general cleanup to updater.py (the file with the many tries) and main.py.   
Utils.py has a seperate Issue assigned to it, so i'll leave it.

**Comment by Double-A-92** [comment]
Does the updater code even work in the current state? It seems buggy all over the place!
E.g. It uses the same content (for the message) for all blog entries that if finds.
And the reddit feed gets cut in the middle of html tags... 

I'll try a complete rewrite. Basically it's just 2 functionalities. Get posts from the official blog, and get posts of reddit users. Right?

**Comment by Double-A-92** [comment]
@zachkont I refactored the whole thing. Could somebody maybe give it another testrun? 
https://github.com/Double-A-92/dotaUpdatesBot/blob/master/updater.py

If everything is good I could send a PR. 

The trys are still there because they are needed. But now they are just in 2 single places.
Also I've changed the log messages... in case they (their error numbers) were relevant for something else.

**Comment by zachkont** [comment]
Wow @Double-A-92 thanks for the effort!
Yeah the updater is functional but probably buggy as hell. A refactor was in my plans so thanks a lot!
Code  looks pretty clean now, well done. 

I do have a question though, why use `threading.Timer()`? It adds the risk of one entry being picked up twice and doesn't really add any value, speed is not an issue here.


By the way, I'm not sure what you mean here:
>E.g. It uses the same content (for the message) for all blog entries that if finds.

And I never bothered with this
>And the reddit feed gets cut in the middle of html tags...

Because it looks like this anyway
![image](https://user-images.githubusercontent.com/17274058/31067497-d252acf6-a75b-11e7-9e1b-8fedc6aee2e8.png)

Is it ok if I create an updater-refactor branch and you send a PR for that so I can test as well?

In any case thanks a lot, good work!

**Comment by Double-A-92** [comment]
@zachkont Sure go ahead and create a refactor branch, I'll send a PR then.

> E.g. It uses the same content (for the message) for all blog entries that if finds.

By that I meant that if there are multiple new posts, the message text is always the text from the first post.
That probably just never happens, because there wont be multiple posts in 3 minutes :)

**Comment by zachkont** [comment]
Oh yeah, I only handled the latest post in the last 3 minutes. I had forgotten all about that... 

The branch is called `updater-refactored`, feel free to make a PR and I'll accept it asap

**Comment by vimarshc** [comment]
Is there more work to be done for this issue? 
@zachkont

**Comment by zachkont** [comment]
Probably not but I haven't had the chance to test yet

**Comment by zachkont** [comment]
Everything looks fine, thank you @Double-A-92 !
