### ISSUE TITLE
Connect to a DynamoDB database on AWS (Option #1)

### ISSUE THREAD

**Issue by comradelemoncake** [zachkont/dotaUpdatesBot#49]
This would be a good option for your database needs. You wouldn't have to move the entire bot onto AWS.

**Comment by zachkont** [comment]
Hmm the free tier is 25GB and 200 million requests, that should be more than enough.

However, I feel that spanning this tiny project over 2 services is overkill, I'd be perfectly happy running mongo or something on the existing server
