### ISSUE TITLE
Provision a MongoDB cluster with Terraform (Option #2)

### ISSUE THREAD

**Issue by comradelemoncake** [zachkont/dotaUpdatesBot#50]
This is another good option for the database. You can use infrastructure as code to set it up.

**Comment by zachkont** [comment]
Haven't heard of terraform before, looks cool.  However, as mentioned on #49 I feel that this is a bit of overkill and in any case the code has to be updated to use mongo first and then we can decide on where the DB will be stored. This feels like a distant future plan, adding something like mongo is a much higher priority for now

**Comment by comradelemoncake** [comment]
Understandable!

**Comment by zachkont** [comment]
Closing for now and we can reopen this when a DB system is added
