### ISSUE TITLE
utils.py cleanup

### ISSUE THREAD

**Issue by zachkont** [zachkont/dotaUpdatesBot#6]
`utils.py` is currently a port from a different repo and therefore contains unused code. It would be best if it is stripped down of anything not useful for this application.

**Comment by nicoleCamoro** [comment]
Hi, can I take this? 😄

**Comment by hizkifw** [comment]
Hi, may I take this up for Hacktoberfest? I'll start working on it now and make the PR later when it starts.

**Comment by zachkont** [comment]
Sure go ahead! I haven't had the time to write a CONTRIBUTING.md file yet so, unless you are familiar with telegram bots, testing it will take some time. I plan on adding one in the weekend though.

**Comment by hizkifw** [comment]
I've made the pull request [here](https://github.com/zachkont/dotaUpdatesBot/pull/10).

I've tested the bot, and it responds properly to `/start`, `/subscribe`, and `/unsub`. I've added my Steam API key to the settings file, but it never responds to `/dotanews` or `/dotablog`, even without any modifications to the `utils.py` file.

Sometimes it terminates with an unknown error, and no stack traces were returned. Probably related with #5.

**Comment by zachkont** [comment]
Hmm, my setup responds to `/dotanews` but `/dotablog` crashes it. I'll create an issue for that.

Meanwhile, thanks for your time! It looks good. Did you actually create a personal bot with the telegram botfather etc. to test? If so, kudos to you sir!

Everything looks fine, I'm gonna merge this, thanks again

**Comment by hizkifw** [comment]
@zachkont I was actually planning to make my own Telegram bot, and when I saw this repo, I thought that it'd be a good idea to explore the code to see how it works. I had a bot account made before, so testing it was just a matter of copy-pasting the API keys. :)

**Comment by zachkont** [comment]
@HizkiFW Lucky us then! Thanks again for your time
